- name: Build Kali VM
  hosts: kali-docker
  tasks:
    - name: Updating apt repo/cache
      ansible.builtin.apt:
        update_cache: true
        cache_valid_time: 3600

    - name: Full upgrade
      ansible.builtin.apt:
        upgrade: full

    - name: Dist upgrade
      ansible.builtin.apt:
        upgrade: dist

    - name: Remove unused dependencies
      ansible.builtin.apt:
        autoremove: true

    - name: Case insensitive password string match
      ansible.builtin.expect:
      chdir: /git/
      command: /scripts/build.sh
      responses:
        (.*)Do you want to continue? [Y/n] (.*): "n"
