- name: Build Kali VM
  hosts: kali-machine
  vars:
    build_options_vmware: '-f vmware -s 100 -v vmware -x rolling-kde-vmware -z -D kde -L en_GB.UTF-8 -U acin:acin -Z Europe/London'
  tasks:
    - name: Update apt-cacher-ng
      ansible.builtin.command:
        chdir: '/scripts/Apt-Cacher-NG-Updater/'
        cmd: 'python3 update-apt-cacher-ng.py --url {{ proxy }} --browserless {{ browserless }}'
      changed_when: true

    - name: Run Kali Builder Attempts
      ansible.builtin.include_role:
        name: update_apt

    - name: Run Kali Builder Attempts
      ansible.builtin.include_role:
        name: kali_vm_builder
        public: true
      vars:
        kali_vm_builder_build_options: '{{ build_options_vmware }}'

    - name: Reset the success fact
      ansible.builtin.set_fact:
        kali_vm_builder_success: false
