- name: Build Kali VM
  hosts: kali-machine
  vars:
    success: false
  tasks:
    - name: Update apt-cacher-ng
      ansible.builtin.command:
        chdir: "/scripts/Apt-Cacher-NG-Updater/"
        cmd: "python3 update-apt-cacher-ng.py --url {{ proxy }} --browserless {{ browserless }}"
      changed_when: true

    - name: Run Kali Builder Attempts
      ansible.builtin.include_role:
        name: update_apt

    - name: Run Kali Builder Attempts
      ansible.builtin.include_role:
        name: kali_vm_builder
      when: not success
      loop:
        - 1
        - 2
        - 3
        - 4
        - 5
