- name: Build Kali VM
  block:
    - name: "Run the kali Build command"
      ansible.builtin.command:
        chdir: "/git/"
        cmd: "/git/build.sh -f vmware -s 100 -v vmware -x rolling-kde-vmware -z -D kde -L en_GB.UTF-8 -U acin:acin -Z Europe/London"
      environment:
        http_proxy: "{{ proxy }}"
      register: build_output
      changed_when: build_output == 0
      when: not success

    - name: Set the success fact
      ansible.builtin.set_fact:
        success: true
      when: not success
  rescue:
    - name: Update apt-cacher-ng
      ansible.builtin.command:
        chdir: "/scripts/Apt-Cacher-NG-Updater/"
        cmd: "python3 update-apt-cacher-ng.py --url {{ proxy }} --browserless {{ browserless }}"
      changed_when: true
