- name: Build Kali VM
  when: not kali_vm_builder_success
  block:
    - name: "Run the kali Build command"
      ansible.builtin.command:
        chdir: "/git/"
        cmd: "/git/build.sh {{ kali_vm_builder_build_options }}"
      environment:
        http_proxy: "{{ proxy }}"
      register: build_output
      changed_when: build_output == 0
      when: not kali_vm_builder_success

    - name: Set the success fact
      ansible.builtin.set_fact:
        kali_vm_builder_success: true
      when: not kali_vm_builder_success
  rescue:
    - name: Update apt-cacher-ng
      ansible.builtin.command:
        chdir: "/scripts/Apt-Cacher-NG-Updater/"
        cmd: "python3 update-apt-cacher-ng.py --url {{ proxy }} --browserless {{ browserless }}"
      changed_when: true
