- name: Create the autostart directory
  ansible.builtin.file:
    path: "{{ config }}/autostart"
    state: directory
    mode: "755"

- name: Copy KDE config files
  ansible.builtin.copy:
    src: "{{ files }}/{{ item.name }}"
    dest: "{{ item.location }}/{{ item.name }}"
    mode: "644"
  loop: "{{ kde_config_files }}"

- name: Check if icon backup exists
  ansible.builtin.stat:
    path: "{{ home }}/.face.bak"
  register: icon_backup

- name: Make original icon backup
  ansible.builtin.copy:
    remote_src: true
    src: "{{ home }}/.face"
    dest: "{{ home }}/.face.bak"
    mode: "644"
  when: not icon_backup.stat.exists

- name: Remove old icon
  ansible.builtin.file:
    path: "{{ home }}/.face"
    state: absent

- name: Link user icon
  ansible.builtin.file:
    src: "{{ icon_location }}"
    dest: "{{ home }}/.face"
    mode: "644"
    state: hard

- name: Copy lockscreen config
  ansible.builtin.template:
    src: "{{ templates }}/{{ item }}.j2"
    dest: "{{ config }}/{{ item }}"
    mode: "644"
  loop:
    - kscreenlockerrc
    - plasma-org.kde.plasma.desktop-appletsrc
