- name: Link configs to folders
  ansible.builtin.file:
    src: "{{ dracula }}/{{ item.application }}/{{ item.name }}"
    dest: "{{ item.destination }}/{{ item.destination_name }}"
    state: link
  when: item.type
  loop: "{{ dracula_config_files }}"
