- name: Dracula theme FZF
  ansible.builtin.shell: fish -c 'set -Ux FZF_DEFAULT_OPTS "--color=fg:#f8f8f2,bg:#282a36,hl:#bd93f9 --color=fg+:#f8f8f2,bg+:#44475a,hl+:#bd93f9 --color=info:#ffb86c,prompt:#50fa7b,pointer:#ff79c6 --color=marker:#ff79c6,spinner:#ffb86c,header:#6272a4"'

- name: Link configs to folders 
  ansible.builtin.file:
    src: "{{ dracula }}/{{ item.application }}/{{ item.name }}"
    dest: "{{ item.destination }}/{{ item.destination_name }}"
    state: link
  loop: "{{ dracula_config_files }}"
  