- name: Check if config exists
  ansible.builtin.stat:
    path: "{{ config }}/bat/config"
  register: bat_config

- name: Create config folder structure
  ansible.builtin.command: "batcat --generate-config-file"
  register: batcat_output
  changed_when: batcat_output.rc == "0"
  when: not bat_config.stat.exists

- name: Insert batcat config
  ansible.builtin.copy:
    src: "{{ files }}/batcat.conf"
    dest: "{{ config }}/bat/config"
    mode: "644"
