- name: Make the VM Fixes
  ansible.builtin.command: "make"
  args:
    chdir: "{{ build }}/Kali-VMware-Fixes"
  register: vmfixes_make_output
  changed_when: vmfixes_make_output.stdout == "gcc -o suid-vm-tools suid-vm-tools.c"
  become: true
  become_method: ansible.builtin.sudo

- name: Set Owner and SUID/SGID
  ansible.builtin.file:
    path: "{{ build }}/Kali-VMware-Fixes/suid-vm-tools"
    mode: "06777"
    owner: root
    group: root
  become: true
  become_method: ansible.builtin.sudo
