- name: Create Ranger config
  ansible.builtin.command: "ranger --copy-config=all"
  register: ranger_config_result
  changed_when:
    - "not ranger_config_result.stderr_lines[0].startswith('already exists:')"

- name: Copy Ranger config files
  ansible.builtin.copy:
    src: "{{ files }}/{{ item.name }}"
    dest: "{{ config }}/ranger/{{ item.name }}"
    mode: "{{ item.mode }}"
  loop:
    - { "name": "scope.sh", "mode": "755" }
    - { "name": "rc.conf", "mode": "644" }

- name: Copy Highlight config files
  ansible.builtin.copy:
    src: "{{ files }}/dracula.theme"
    dest: "/usr/share/highlight/themes/dracula.theme"
    mode: "644"
  become: true
  become_method: ansible.builtin.sudo

- name: Create the colorscheme directory
  ansible.builtin.file:
    path: "{{ config }}/ranger/colorschemes"
    state: directory
    mode: "755"
