---
# tasks file for configure-kali
- name: Create file structure
  ansible.builtin.import_tasks:
    file: create_structure.yml

- name: Configure Ranger
  ansible.builtin.import_tasks:
    file: configure_ranger.yml

- name: Configure Dracula
  ansible.builtin.import_tasks:
    file: configure_dracula.yml

- name: Configure Fish
  ansible.builtin.import_tasks:
    file: configure_fish.yml

- name: Configure Neovim
  ansible.builtin.import_tasks:
    file: configure_neovim.yml

- name: Configure Btop
  ansible.builtin.import_tasks:
    file: configure_btop.yml

- name: Configure Tmux
  ansible.builtin.import_tasks:
    file: configure_tmux.yml

- name: Configure Batcat
  ansible.builtin.import_tasks:
    file: configure_batcat.yml
