---
# tasks file for configure-kali
- name: Configure Grub
  ansible.builtin.import_tasks:
    file: configure_grub.yml

- name: Reboot after updates
  ansible.builtin.reboot:
    reboot_timeout: 3600
  become: true
  become_method: ansible.builtin.sudo
  when: not wsl and cache_update.changed

- name: Install apt packages
  ansible.builtin.import_tasks:
    file: install_packages.yml

- name: Create file structure
  ansible.builtin.import_tasks:
    file: create_structure.yml

- name: Install web packages
  ansible.builtin.import_tasks:
    file: install_web_packages.yml

- name: Install git packages
  ansible.builtin.import_tasks:
    file: install_git_packages.yml

- name: Configure Ranger
  ansible.builtin.import_tasks:
    file: configure_ranger.yml

- name: Configure Dracula
  ansible.builtin.import_tasks:
    file: configure_dracula.yml

- name: Configure Fish
  ansible.builtin.import_tasks:
    file: configure_fish.yml

- name: Configure Neovim
  ansible.builtin.import_tasks:
    file: configure_neovim.yml

- name: Configure Btop
  ansible.builtin.import_tasks:
    file: configure_btop.yml

- name: Configure VM tools
  ansible.builtin.import_tasks:
    file: configure_vm.yml
  when: vm

- name: Configure KDE
  ansible.builtin.import_tasks:
    file: configure_kde.yml
  when: kde

- name: Configure Tmux
  ansible.builtin.import_tasks:
    file: configure_tmux.yml

- name: Configure Batcat
  ansible.builtin.import_tasks:
    file: configure_batcat.yml

- name: Configure SDDM
  ansible.builtin.import_tasks:
    file: configure_sddm.yml
  when: kde
