- name: Create The Lingolo Directories
  ansible.builtin.file:
    path: "{{ install_web_packages_home }}/Documents/Host/{{ item }}"
    state: directory
    mode: "755"
  loop:
    - "Ligolo/Agent/OSX/ARM"
    - "Ligolo/Agent/Linux/ARM/v6"
    - "Ligolo/Agent/Linux/ARM/v7"
    - "Ligolo/Agent/Windows/ARM/v6"
    - "Ligolo/Agent/Windows/ARM/v7"
    - "Ligolo/Proxy/OSX/ARM"
    - "Ligolo/Proxy/Linux/ARM"
    - "Ligolo/Proxy/Windows/ARM"

- name: Get Ligolo-ng Version
  ansible.builtin.uri:
    url: https://github.com/nicocha30/ligolo-ng/releases/latest
  register: ligolo_version_output

- name: Setting Ligolo-ng Version
  ansible.builtin.set_fact:
    ligolo_version: "{{ ligolo_version_output.url | split('v') | last }}"

- name: Setting Ligolo-ng Files
  ansible.builtin.set_fact:
    ligolo:
      - name: "ligolo-ng_agent_{{ ligolo_version }}_darwin_amd64"
        extension: "tar.gz"
        type: "Agent"
        os: "OSX"
        arc: ""
      - name: "ligolo-ng_agent_{{ ligolo_version }}_darwin_arm64"
        extension: "tar.gz"
        type: "Agent"
        os: "OSX"
        arc: "ARM"
      - name: "ligolo-ng_agent_{{ ligolo_version }}_linux_amd64"
        extension: "tar.gz"
        type: "Agent"
        os: "Linux"
        arc: ""
      - name: "ligolo-ng_agent_{{ ligolo_version }}_linux_arm64"
        extension: "tar.gz"
        type: "Agent"
        os: "Linux"
        arc: "ARM"
      - name: "ligolo-ng_agent_{{ ligolo_version }}_linux_armv6"
        extension: "tar.gz"
        type: "Agent"
        os: "Linux"
        arc: "ARM/v6"
      - name: "ligolo-ng_agent_{{ ligolo_version }}_linux_armv7"
        extension: "tar.gz"
        type: "Agent"
        os: "Linux"
        arc: "ARM/v7"
      - name: "ligolo-ng_agent_{{ ligolo_version }}_windows_amd64"
        extension: "zip"
        type: "Agent"
        os: "Windows"
        arc: ""
      - name: "ligolo-ng_agent_{{ ligolo_version }}_windows_arm64"
        extension: "zip"
        type: "Agent"
        os: "Windows"
        arc: "ARM"
      - name: "ligolo-ng_agent_{{ ligolo_version }}_windows_armv6"
        extension: "zip"
        type: "Agent"
        os: "Windows"
        arc: "ARM/v6"
      - name: "ligolo-ng_agent_{{ ligolo_version }}_windows_armv7"
        extension: "zip"
        type: "Agent"
        os: "Windows"
        arc: "ARM/v7"
      - name: "ligolo-ng_proxy_{{ ligolo_version }}_darwin_amd64"
        extension: "tar.gz"
        type: "Proxy"
        os: "OSX"
        arc: ""
      - name: "ligolo-ng_proxy_{{ ligolo_version }}_darwin_arm64"
        extension: "tar.gz"
        type: "Proxy"
        os: "OSX"
        arc: "ARM"
      - name: "ligolo-ng_proxy_{{ ligolo_version }}_linux_amd64"
        extension: "tar.gz"
        type: "Proxy"
        os: "Linux"
        arc: ""
      - name: "ligolo-ng_proxy_{{ ligolo_version }}_linux_arm64"
        extension: "tar.gz"
        type: "Proxy"
        os: "Linux"
        arc: "ARM"
      - name: "ligolo-ng_proxy_{{ ligolo_version }}_windows_amd64"
        extension: "zip"
        type: "Proxy"
        os: "Windows"
        arc: ""
      - name: "ligolo-ng_proxy_{{ ligolo_version }}_windows_arm64"
        extension: "zip"
        type: "Proxy"
        os: "Windows"
        arc: "ARM"

- name: Download and Unarchive Ligolo
  ansible.builtin.unarchive:
    src: "https://github.com/nicocha30/ligolo-ng/releases/download/v{{ ligolo_version }}/{{ item.name }}.{{ item.extension }}"
    dest: "{{ install_web_packages_home }}/Documents/Host/Ligolo/{{ item.type }}/{{ item.os }}/{{ item.arc }}"
    remote_src: true
    mode: '755'
  loop: "{{ ligolo }}"
